#coding:utf-8
# 2014-12-18
# build by qianqians
# deletenonespacelstrip

def deleteNoneSpacelstrip(str):
    while(str.lstrip('\r') is not str):str = str.lstrip('\r')
    while(str.lstrip('\n') is not str):str = str.lstrip('\n')
    while(str.lstrip('\t') is not str):str = str.lstrip('\t')
    while(str.lstrip('\t') is not str):str = str.lstrip('\r\n')
    while(str.lstrip('\0') is not str):str = str.lstrip('\0')
    while(str.lstrip('\r') is not str):str = str.lstrip('\r')
    while(str.lstrip('\n') is not str):str = str.lstrip('\n')
    while(str.lstrip('\t') is not str):str = str.lstrip('\t')
    while(str.lstrip('\t') is not str):str = str.lstrip('\r\n')
    while(str.lstrip('\0') is not str):str = str.lstrip('\0')
    while(str.lstrip('\r') is not str):str = str.lstrip('\r')
    while(str.lstrip('\n') is not str):str = str.lstrip('\n')
    while(str.lstrip('\t') is not str):str = str.lstrip('\t')
    while(str.lstrip('\t') is not str):str = str.lstrip('\r\n')
    while(str.lstrip('\0') is not str):str = str.lstrip('\0')
    while(str.lstrip('\r') is not str):str = str.lstrip('\r')
    while(str.lstrip('\n') is not str):str = str.lstrip('\n')
    while(str.lstrip('\t') is not str):str = str.lstrip('\t')
    while(str.lstrip('\t') is not str):str = str.lstrip('\r\n')
    while(str.lstrip('\0') is not str):str = str.lstrip('\0')
    while(str.lstrip('\r') is not str):str = str.lstrip('\r')
    while(str.lstrip('\n') is not str):str = str.lstrip('\n')
    while(str.lstrip('\t') is not str):str = str.lstrip('\t')
    while(str.lstrip('\t') is not str):str = str.lstrip('\r\n')
    while(str.lstrip('\0') is not str):str = str.lstrip('\0')
    while(str.lstrip('	') is not str):str = str.lstrip('	')
    while(str.lstrip(' ') is not str):str = str.lstrip(' ')
    while(str.lstrip('	') is not str):str = str.lstrip('	')
    while(str.rstrip('\r') is not str):str = str.rstrip('\r')
    while(str.rstrip('\n') is not str):str = str.rstrip('\n')
    while(str.rstrip('\n') is not str):str = str.rstrip('\r\n')
    while(str.rstrip('\t') is not str):str = str.rstrip('\t')
    while(str.rstrip('\0') is not str):str = str.rstrip('\0')
    while(str.rstrip('\r') is not str):str = str.rstrip('\r')
    while(str.rstrip('\n') is not str):str = str.rstrip('\n')
    while(str.rstrip('\n') is not str):str = str.rstrip('\r\n')
    while(str.rstrip('\t') is not str):str = str.rstrip('\t')
    while(str.rstrip('\0') is not str):str = str.rstrip('\0')
    while(str.rstrip('\r') is not str):str = str.rstrip('\r')
    while(str.rstrip('\n') is not str):str = str.rstrip('\n')
    while(str.rstrip('\n') is not str):str = str.rstrip('\r\n')
    while(str.rstrip('\t') is not str):str = str.rstrip('\t')
    while(str.rstrip('\0') is not str):str = str.rstrip('\0')
    while(str.rstrip('\r') is not str):str = str.rstrip('\r')
    while(str.rstrip('\n') is not str):str = str.rstrip('\n')
    while(str.rstrip('\n') is not str):str = str.rstrip('\r\n')
    while(str.rstrip('\t') is not str):str = str.rstrip('\t')
    while(str.rstrip('\0') is not str):str = str.rstrip('\0')
    while(str.rstrip('\r') is not str):str = str.rstrip('\r')
    while(str.rstrip('\n') is not str):str = str.rstrip('\n')
    while(str.rstrip('\n') is not str):str = str.rstrip('\r\n')
    while(str.rstrip('\t') is not str):str = str.rstrip('\t')
    while(str.rstrip('\0') is not str):str = str.rstrip('\0')
    while(str.rstrip('	') is not str):str = str.rstrip('	')
    while(str.rstrip(' ') is not str):str = str.rstrip(' ')
    while(str.rstrip('	') is not str):str = str.rstrip('	')
    return str