// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dbproxy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from dbproxy.proto</summary>
public static partial class DbproxyReflection {

  #region Descriptor
  /// <summary>File descriptor for dbproxy.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DbproxyReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1kYnByb3h5LnByb3RvIjoKBkRCSW5mbxIQCghpbnN0YW5jZRgBIAEoCRIK",
          "CgJkYhgCIAEoCRISCgpjb2xsZWN0aW9uGAMgASgJIj0KDEdldEd1aWRFdmVu",
          "dBIYCgdkYl9JbmZvGAEgASgLMgcuREJJbmZvEhMKC2NhbGxiYWNrX2lkGAIg",
          "ASgJIlcKEUNyZWF0ZU9iamVjdEV2ZW50EhgKB2RiX0luZm8YASABKAsyBy5E",
          "QkluZm8SEwoLY2FsbGJhY2tfaWQYAiABKAkSEwoLb2JqZWN0X2luZm8YAyAB",
          "KAwifgoRVXBkYXRlT2JqZWN0RXZlbnQSGAoHZGJfSW5mbxgBIAEoCzIHLkRC",
          "SW5mbxITCgtjYWxsYmFja19pZBgCIAEoCRISCgpxdWVyeV9pbmZvGAMgASgM",
          "EhMKC3VwZGF0YV9pbmZvGAQgASgMEhEKCWlzX3Vwc2VydBgFIAEoCCKPAQoS",
          "RmluZEFuZE1vZGlmeUV2ZW50EhgKB2RiX0luZm8YASABKAsyBy5EQkluZm8S",
          "EwoLY2FsbGJhY2tfaWQYAiABKAkSEgoKcXVlcnlfaW5mbxgDIAEoDBITCgt1",
          "cGRhdGFfaW5mbxgEIAEoDBIOCgZpc19uZXcYBSABKAgSEQoJaXNfdXBzZXJ0",
          "GAYgASgIIlYKEVJlbW92ZU9iamVjdEV2ZW50EhgKB2RiX0luZm8YASABKAsy",
          "By5EQkluZm8SEwoLY2FsbGJhY2tfaWQYAiABKAkSEgoKcXVlcnlfaW5mbxgD",
          "IAEoDCKVAQoSR2V0T2JqZWN0SW5mb0V2ZW50EhgKB2RiX0luZm8YASABKAsy",
          "By5EQkluZm8SEwoLY2FsbGJhY2tfaWQYAiABKAkSEgoKcXVlcnlfaW5mbxgD",
          "IAEoDBIMCgRza2lwGAQgASgNEg0KBWxpbWl0GAUgASgNEgwKBHNvcnQYBiAB",
          "KAkSEQoJYXNjZW5kaW5nGAcgASgIIlgKE0dldE9iamVjdENvdW50RXZlbnQS",
          "GAoHZGJfSW5mbxgBIAEoCzIHLkRCSW5mbxITCgtjYWxsYmFja19pZBgCIAEo",
          "CRISCgpxdWVyeV9pbmZvGAMgASgMYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DBInfo), global::DBInfo.Parser, new[]{ "Instance", "Db", "Collection" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GetGuidEvent), global::GetGuidEvent.Parser, new[]{ "DbInfo", "CallbackId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CreateObjectEvent), global::CreateObjectEvent.Parser, new[]{ "DbInfo", "CallbackId", "ObjectInfo" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UpdateObjectEvent), global::UpdateObjectEvent.Parser, new[]{ "DbInfo", "CallbackId", "QueryInfo", "UpdataInfo", "IsUpsert" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FindAndModifyEvent), global::FindAndModifyEvent.Parser, new[]{ "DbInfo", "CallbackId", "QueryInfo", "UpdataInfo", "IsNew", "IsUpsert" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RemoveObjectEvent), global::RemoveObjectEvent.Parser, new[]{ "DbInfo", "CallbackId", "QueryInfo" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GetObjectInfoEvent), global::GetObjectInfoEvent.Parser, new[]{ "DbInfo", "CallbackId", "QueryInfo", "Skip", "Limit", "Sort", "Ascending" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GetObjectCountEvent), global::GetObjectCountEvent.Parser, new[]{ "DbInfo", "CallbackId", "QueryInfo" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class DBInfo : pb::IMessage<DBInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DBInfo> _parser = new pb::MessageParser<DBInfo>(() => new DBInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DBInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DBInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DBInfo(DBInfo other) : this() {
    instance_ = other.instance_;
    db_ = other.db_;
    collection_ = other.collection_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DBInfo Clone() {
    return new DBInfo(this);
  }

  /// <summary>Field number for the "instance" field.</summary>
  public const int InstanceFieldNumber = 1;
  private string instance_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Instance {
    get { return instance_; }
    set {
      instance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "db" field.</summary>
  public const int DbFieldNumber = 2;
  private string db_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Db {
    get { return db_; }
    set {
      db_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "collection" field.</summary>
  public const int CollectionFieldNumber = 3;
  private string collection_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Collection {
    get { return collection_; }
    set {
      collection_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DBInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DBInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Instance != other.Instance) return false;
    if (Db != other.Db) return false;
    if (Collection != other.Collection) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Instance.Length != 0) hash ^= Instance.GetHashCode();
    if (Db.Length != 0) hash ^= Db.GetHashCode();
    if (Collection.Length != 0) hash ^= Collection.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Instance.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Instance);
    }
    if (Db.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Db);
    }
    if (Collection.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Collection);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Instance.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Instance);
    }
    if (Db.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Db);
    }
    if (Collection.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Collection);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Instance.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Instance);
    }
    if (Db.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Db);
    }
    if (Collection.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Collection);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DBInfo other) {
    if (other == null) {
      return;
    }
    if (other.Instance.Length != 0) {
      Instance = other.Instance;
    }
    if (other.Db.Length != 0) {
      Db = other.Db;
    }
    if (other.Collection.Length != 0) {
      Collection = other.Collection;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Instance = input.ReadString();
          break;
        }
        case 18: {
          Db = input.ReadString();
          break;
        }
        case 26: {
          Collection = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Instance = input.ReadString();
          break;
        }
        case 18: {
          Db = input.ReadString();
          break;
        }
        case 26: {
          Collection = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GetGuidEvent : pb::IMessage<GetGuidEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetGuidEvent> _parser = new pb::MessageParser<GetGuidEvent>(() => new GetGuidEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetGuidEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGuidEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGuidEvent(GetGuidEvent other) : this() {
    dbInfo_ = other.dbInfo_ != null ? other.dbInfo_.Clone() : null;
    callbackId_ = other.callbackId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGuidEvent Clone() {
    return new GetGuidEvent(this);
  }

  /// <summary>Field number for the "db_Info" field.</summary>
  public const int DbInfoFieldNumber = 1;
  private global::DBInfo dbInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DBInfo DbInfo {
    get { return dbInfo_; }
    set {
      dbInfo_ = value;
    }
  }

  /// <summary>Field number for the "callback_id" field.</summary>
  public const int CallbackIdFieldNumber = 2;
  private string callbackId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CallbackId {
    get { return callbackId_; }
    set {
      callbackId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetGuidEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetGuidEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DbInfo, other.DbInfo)) return false;
    if (CallbackId != other.CallbackId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (dbInfo_ != null) hash ^= DbInfo.GetHashCode();
    if (CallbackId.Length != 0) hash ^= CallbackId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (dbInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DbInfo);
    }
    if (CallbackId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CallbackId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetGuidEvent other) {
    if (other == null) {
      return;
    }
    if (other.dbInfo_ != null) {
      if (dbInfo_ == null) {
        DbInfo = new global::DBInfo();
      }
      DbInfo.MergeFrom(other.DbInfo);
    }
    if (other.CallbackId.Length != 0) {
      CallbackId = other.CallbackId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class CreateObjectEvent : pb::IMessage<CreateObjectEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CreateObjectEvent> _parser = new pb::MessageParser<CreateObjectEvent>(() => new CreateObjectEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CreateObjectEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CreateObjectEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CreateObjectEvent(CreateObjectEvent other) : this() {
    dbInfo_ = other.dbInfo_ != null ? other.dbInfo_.Clone() : null;
    callbackId_ = other.callbackId_;
    objectInfo_ = other.objectInfo_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CreateObjectEvent Clone() {
    return new CreateObjectEvent(this);
  }

  /// <summary>Field number for the "db_Info" field.</summary>
  public const int DbInfoFieldNumber = 1;
  private global::DBInfo dbInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DBInfo DbInfo {
    get { return dbInfo_; }
    set {
      dbInfo_ = value;
    }
  }

  /// <summary>Field number for the "callback_id" field.</summary>
  public const int CallbackIdFieldNumber = 2;
  private string callbackId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CallbackId {
    get { return callbackId_; }
    set {
      callbackId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "object_info" field.</summary>
  public const int ObjectInfoFieldNumber = 3;
  private pb::ByteString objectInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ObjectInfo {
    get { return objectInfo_; }
    set {
      objectInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CreateObjectEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CreateObjectEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DbInfo, other.DbInfo)) return false;
    if (CallbackId != other.CallbackId) return false;
    if (ObjectInfo != other.ObjectInfo) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (dbInfo_ != null) hash ^= DbInfo.GetHashCode();
    if (CallbackId.Length != 0) hash ^= CallbackId.GetHashCode();
    if (ObjectInfo.Length != 0) hash ^= ObjectInfo.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (ObjectInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(ObjectInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (ObjectInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(ObjectInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (dbInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DbInfo);
    }
    if (CallbackId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CallbackId);
    }
    if (ObjectInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ObjectInfo);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CreateObjectEvent other) {
    if (other == null) {
      return;
    }
    if (other.dbInfo_ != null) {
      if (dbInfo_ == null) {
        DbInfo = new global::DBInfo();
      }
      DbInfo.MergeFrom(other.DbInfo);
    }
    if (other.CallbackId.Length != 0) {
      CallbackId = other.CallbackId;
    }
    if (other.ObjectInfo.Length != 0) {
      ObjectInfo = other.ObjectInfo;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          ObjectInfo = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          ObjectInfo = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class UpdateObjectEvent : pb::IMessage<UpdateObjectEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UpdateObjectEvent> _parser = new pb::MessageParser<UpdateObjectEvent>(() => new UpdateObjectEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UpdateObjectEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UpdateObjectEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UpdateObjectEvent(UpdateObjectEvent other) : this() {
    dbInfo_ = other.dbInfo_ != null ? other.dbInfo_.Clone() : null;
    callbackId_ = other.callbackId_;
    queryInfo_ = other.queryInfo_;
    updataInfo_ = other.updataInfo_;
    isUpsert_ = other.isUpsert_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UpdateObjectEvent Clone() {
    return new UpdateObjectEvent(this);
  }

  /// <summary>Field number for the "db_Info" field.</summary>
  public const int DbInfoFieldNumber = 1;
  private global::DBInfo dbInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DBInfo DbInfo {
    get { return dbInfo_; }
    set {
      dbInfo_ = value;
    }
  }

  /// <summary>Field number for the "callback_id" field.</summary>
  public const int CallbackIdFieldNumber = 2;
  private string callbackId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CallbackId {
    get { return callbackId_; }
    set {
      callbackId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "query_info" field.</summary>
  public const int QueryInfoFieldNumber = 3;
  private pb::ByteString queryInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString QueryInfo {
    get { return queryInfo_; }
    set {
      queryInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "updata_info" field.</summary>
  public const int UpdataInfoFieldNumber = 4;
  private pb::ByteString updataInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString UpdataInfo {
    get { return updataInfo_; }
    set {
      updataInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_upsert" field.</summary>
  public const int IsUpsertFieldNumber = 5;
  private bool isUpsert_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsUpsert {
    get { return isUpsert_; }
    set {
      isUpsert_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UpdateObjectEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UpdateObjectEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DbInfo, other.DbInfo)) return false;
    if (CallbackId != other.CallbackId) return false;
    if (QueryInfo != other.QueryInfo) return false;
    if (UpdataInfo != other.UpdataInfo) return false;
    if (IsUpsert != other.IsUpsert) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (dbInfo_ != null) hash ^= DbInfo.GetHashCode();
    if (CallbackId.Length != 0) hash ^= CallbackId.GetHashCode();
    if (QueryInfo.Length != 0) hash ^= QueryInfo.GetHashCode();
    if (UpdataInfo.Length != 0) hash ^= UpdataInfo.GetHashCode();
    if (IsUpsert != false) hash ^= IsUpsert.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (UpdataInfo.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(UpdataInfo);
    }
    if (IsUpsert != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsUpsert);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (UpdataInfo.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(UpdataInfo);
    }
    if (IsUpsert != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsUpsert);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (dbInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DbInfo);
    }
    if (CallbackId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(QueryInfo);
    }
    if (UpdataInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(UpdataInfo);
    }
    if (IsUpsert != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UpdateObjectEvent other) {
    if (other == null) {
      return;
    }
    if (other.dbInfo_ != null) {
      if (dbInfo_ == null) {
        DbInfo = new global::DBInfo();
      }
      DbInfo.MergeFrom(other.DbInfo);
    }
    if (other.CallbackId.Length != 0) {
      CallbackId = other.CallbackId;
    }
    if (other.QueryInfo.Length != 0) {
      QueryInfo = other.QueryInfo;
    }
    if (other.UpdataInfo.Length != 0) {
      UpdataInfo = other.UpdataInfo;
    }
    if (other.IsUpsert != false) {
      IsUpsert = other.IsUpsert;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
        case 34: {
          UpdataInfo = input.ReadBytes();
          break;
        }
        case 40: {
          IsUpsert = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
        case 34: {
          UpdataInfo = input.ReadBytes();
          break;
        }
        case 40: {
          IsUpsert = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FindAndModifyEvent : pb::IMessage<FindAndModifyEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FindAndModifyEvent> _parser = new pb::MessageParser<FindAndModifyEvent>(() => new FindAndModifyEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FindAndModifyEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FindAndModifyEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FindAndModifyEvent(FindAndModifyEvent other) : this() {
    dbInfo_ = other.dbInfo_ != null ? other.dbInfo_.Clone() : null;
    callbackId_ = other.callbackId_;
    queryInfo_ = other.queryInfo_;
    updataInfo_ = other.updataInfo_;
    isNew_ = other.isNew_;
    isUpsert_ = other.isUpsert_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FindAndModifyEvent Clone() {
    return new FindAndModifyEvent(this);
  }

  /// <summary>Field number for the "db_Info" field.</summary>
  public const int DbInfoFieldNumber = 1;
  private global::DBInfo dbInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DBInfo DbInfo {
    get { return dbInfo_; }
    set {
      dbInfo_ = value;
    }
  }

  /// <summary>Field number for the "callback_id" field.</summary>
  public const int CallbackIdFieldNumber = 2;
  private string callbackId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CallbackId {
    get { return callbackId_; }
    set {
      callbackId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "query_info" field.</summary>
  public const int QueryInfoFieldNumber = 3;
  private pb::ByteString queryInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString QueryInfo {
    get { return queryInfo_; }
    set {
      queryInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "updata_info" field.</summary>
  public const int UpdataInfoFieldNumber = 4;
  private pb::ByteString updataInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString UpdataInfo {
    get { return updataInfo_; }
    set {
      updataInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_new" field.</summary>
  public const int IsNewFieldNumber = 5;
  private bool isNew_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsNew {
    get { return isNew_; }
    set {
      isNew_ = value;
    }
  }

  /// <summary>Field number for the "is_upsert" field.</summary>
  public const int IsUpsertFieldNumber = 6;
  private bool isUpsert_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsUpsert {
    get { return isUpsert_; }
    set {
      isUpsert_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FindAndModifyEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FindAndModifyEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DbInfo, other.DbInfo)) return false;
    if (CallbackId != other.CallbackId) return false;
    if (QueryInfo != other.QueryInfo) return false;
    if (UpdataInfo != other.UpdataInfo) return false;
    if (IsNew != other.IsNew) return false;
    if (IsUpsert != other.IsUpsert) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (dbInfo_ != null) hash ^= DbInfo.GetHashCode();
    if (CallbackId.Length != 0) hash ^= CallbackId.GetHashCode();
    if (QueryInfo.Length != 0) hash ^= QueryInfo.GetHashCode();
    if (UpdataInfo.Length != 0) hash ^= UpdataInfo.GetHashCode();
    if (IsNew != false) hash ^= IsNew.GetHashCode();
    if (IsUpsert != false) hash ^= IsUpsert.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (UpdataInfo.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(UpdataInfo);
    }
    if (IsNew != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsNew);
    }
    if (IsUpsert != false) {
      output.WriteRawTag(48);
      output.WriteBool(IsUpsert);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (UpdataInfo.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(UpdataInfo);
    }
    if (IsNew != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsNew);
    }
    if (IsUpsert != false) {
      output.WriteRawTag(48);
      output.WriteBool(IsUpsert);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (dbInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DbInfo);
    }
    if (CallbackId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(QueryInfo);
    }
    if (UpdataInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(UpdataInfo);
    }
    if (IsNew != false) {
      size += 1 + 1;
    }
    if (IsUpsert != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FindAndModifyEvent other) {
    if (other == null) {
      return;
    }
    if (other.dbInfo_ != null) {
      if (dbInfo_ == null) {
        DbInfo = new global::DBInfo();
      }
      DbInfo.MergeFrom(other.DbInfo);
    }
    if (other.CallbackId.Length != 0) {
      CallbackId = other.CallbackId;
    }
    if (other.QueryInfo.Length != 0) {
      QueryInfo = other.QueryInfo;
    }
    if (other.UpdataInfo.Length != 0) {
      UpdataInfo = other.UpdataInfo;
    }
    if (other.IsNew != false) {
      IsNew = other.IsNew;
    }
    if (other.IsUpsert != false) {
      IsUpsert = other.IsUpsert;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
        case 34: {
          UpdataInfo = input.ReadBytes();
          break;
        }
        case 40: {
          IsNew = input.ReadBool();
          break;
        }
        case 48: {
          IsUpsert = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
        case 34: {
          UpdataInfo = input.ReadBytes();
          break;
        }
        case 40: {
          IsNew = input.ReadBool();
          break;
        }
        case 48: {
          IsUpsert = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class RemoveObjectEvent : pb::IMessage<RemoveObjectEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RemoveObjectEvent> _parser = new pb::MessageParser<RemoveObjectEvent>(() => new RemoveObjectEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RemoveObjectEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RemoveObjectEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RemoveObjectEvent(RemoveObjectEvent other) : this() {
    dbInfo_ = other.dbInfo_ != null ? other.dbInfo_.Clone() : null;
    callbackId_ = other.callbackId_;
    queryInfo_ = other.queryInfo_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RemoveObjectEvent Clone() {
    return new RemoveObjectEvent(this);
  }

  /// <summary>Field number for the "db_Info" field.</summary>
  public const int DbInfoFieldNumber = 1;
  private global::DBInfo dbInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DBInfo DbInfo {
    get { return dbInfo_; }
    set {
      dbInfo_ = value;
    }
  }

  /// <summary>Field number for the "callback_id" field.</summary>
  public const int CallbackIdFieldNumber = 2;
  private string callbackId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CallbackId {
    get { return callbackId_; }
    set {
      callbackId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "query_info" field.</summary>
  public const int QueryInfoFieldNumber = 3;
  private pb::ByteString queryInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString QueryInfo {
    get { return queryInfo_; }
    set {
      queryInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RemoveObjectEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RemoveObjectEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DbInfo, other.DbInfo)) return false;
    if (CallbackId != other.CallbackId) return false;
    if (QueryInfo != other.QueryInfo) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (dbInfo_ != null) hash ^= DbInfo.GetHashCode();
    if (CallbackId.Length != 0) hash ^= CallbackId.GetHashCode();
    if (QueryInfo.Length != 0) hash ^= QueryInfo.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (dbInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DbInfo);
    }
    if (CallbackId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(QueryInfo);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RemoveObjectEvent other) {
    if (other == null) {
      return;
    }
    if (other.dbInfo_ != null) {
      if (dbInfo_ == null) {
        DbInfo = new global::DBInfo();
      }
      DbInfo.MergeFrom(other.DbInfo);
    }
    if (other.CallbackId.Length != 0) {
      CallbackId = other.CallbackId;
    }
    if (other.QueryInfo.Length != 0) {
      QueryInfo = other.QueryInfo;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GetObjectInfoEvent : pb::IMessage<GetObjectInfoEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetObjectInfoEvent> _parser = new pb::MessageParser<GetObjectInfoEvent>(() => new GetObjectInfoEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetObjectInfoEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetObjectInfoEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetObjectInfoEvent(GetObjectInfoEvent other) : this() {
    dbInfo_ = other.dbInfo_ != null ? other.dbInfo_.Clone() : null;
    callbackId_ = other.callbackId_;
    queryInfo_ = other.queryInfo_;
    skip_ = other.skip_;
    limit_ = other.limit_;
    sort_ = other.sort_;
    ascending_ = other.ascending_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetObjectInfoEvent Clone() {
    return new GetObjectInfoEvent(this);
  }

  /// <summary>Field number for the "db_Info" field.</summary>
  public const int DbInfoFieldNumber = 1;
  private global::DBInfo dbInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DBInfo DbInfo {
    get { return dbInfo_; }
    set {
      dbInfo_ = value;
    }
  }

  /// <summary>Field number for the "callback_id" field.</summary>
  public const int CallbackIdFieldNumber = 2;
  private string callbackId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CallbackId {
    get { return callbackId_; }
    set {
      callbackId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "query_info" field.</summary>
  public const int QueryInfoFieldNumber = 3;
  private pb::ByteString queryInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString QueryInfo {
    get { return queryInfo_; }
    set {
      queryInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "skip" field.</summary>
  public const int SkipFieldNumber = 4;
  private uint skip_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Skip {
    get { return skip_; }
    set {
      skip_ = value;
    }
  }

  /// <summary>Field number for the "limit" field.</summary>
  public const int LimitFieldNumber = 5;
  private uint limit_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Limit {
    get { return limit_; }
    set {
      limit_ = value;
    }
  }

  /// <summary>Field number for the "sort" field.</summary>
  public const int SortFieldNumber = 6;
  private string sort_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Sort {
    get { return sort_; }
    set {
      sort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ascending" field.</summary>
  public const int AscendingFieldNumber = 7;
  private bool ascending_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Ascending {
    get { return ascending_; }
    set {
      ascending_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetObjectInfoEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetObjectInfoEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DbInfo, other.DbInfo)) return false;
    if (CallbackId != other.CallbackId) return false;
    if (QueryInfo != other.QueryInfo) return false;
    if (Skip != other.Skip) return false;
    if (Limit != other.Limit) return false;
    if (Sort != other.Sort) return false;
    if (Ascending != other.Ascending) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (dbInfo_ != null) hash ^= DbInfo.GetHashCode();
    if (CallbackId.Length != 0) hash ^= CallbackId.GetHashCode();
    if (QueryInfo.Length != 0) hash ^= QueryInfo.GetHashCode();
    if (Skip != 0) hash ^= Skip.GetHashCode();
    if (Limit != 0) hash ^= Limit.GetHashCode();
    if (Sort.Length != 0) hash ^= Sort.GetHashCode();
    if (Ascending != false) hash ^= Ascending.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (Skip != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Skip);
    }
    if (Limit != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(Limit);
    }
    if (Sort.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Sort);
    }
    if (Ascending != false) {
      output.WriteRawTag(56);
      output.WriteBool(Ascending);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (Skip != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Skip);
    }
    if (Limit != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(Limit);
    }
    if (Sort.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Sort);
    }
    if (Ascending != false) {
      output.WriteRawTag(56);
      output.WriteBool(Ascending);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (dbInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DbInfo);
    }
    if (CallbackId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(QueryInfo);
    }
    if (Skip != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Skip);
    }
    if (Limit != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Limit);
    }
    if (Sort.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Sort);
    }
    if (Ascending != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetObjectInfoEvent other) {
    if (other == null) {
      return;
    }
    if (other.dbInfo_ != null) {
      if (dbInfo_ == null) {
        DbInfo = new global::DBInfo();
      }
      DbInfo.MergeFrom(other.DbInfo);
    }
    if (other.CallbackId.Length != 0) {
      CallbackId = other.CallbackId;
    }
    if (other.QueryInfo.Length != 0) {
      QueryInfo = other.QueryInfo;
    }
    if (other.Skip != 0) {
      Skip = other.Skip;
    }
    if (other.Limit != 0) {
      Limit = other.Limit;
    }
    if (other.Sort.Length != 0) {
      Sort = other.Sort;
    }
    if (other.Ascending != false) {
      Ascending = other.Ascending;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
        case 32: {
          Skip = input.ReadUInt32();
          break;
        }
        case 40: {
          Limit = input.ReadUInt32();
          break;
        }
        case 50: {
          Sort = input.ReadString();
          break;
        }
        case 56: {
          Ascending = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
        case 32: {
          Skip = input.ReadUInt32();
          break;
        }
        case 40: {
          Limit = input.ReadUInt32();
          break;
        }
        case 50: {
          Sort = input.ReadString();
          break;
        }
        case 56: {
          Ascending = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GetObjectCountEvent : pb::IMessage<GetObjectCountEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetObjectCountEvent> _parser = new pb::MessageParser<GetObjectCountEvent>(() => new GetObjectCountEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetObjectCountEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DbproxyReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetObjectCountEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetObjectCountEvent(GetObjectCountEvent other) : this() {
    dbInfo_ = other.dbInfo_ != null ? other.dbInfo_.Clone() : null;
    callbackId_ = other.callbackId_;
    queryInfo_ = other.queryInfo_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetObjectCountEvent Clone() {
    return new GetObjectCountEvent(this);
  }

  /// <summary>Field number for the "db_Info" field.</summary>
  public const int DbInfoFieldNumber = 1;
  private global::DBInfo dbInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DBInfo DbInfo {
    get { return dbInfo_; }
    set {
      dbInfo_ = value;
    }
  }

  /// <summary>Field number for the "callback_id" field.</summary>
  public const int CallbackIdFieldNumber = 2;
  private string callbackId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CallbackId {
    get { return callbackId_; }
    set {
      callbackId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "query_info" field.</summary>
  public const int QueryInfoFieldNumber = 3;
  private pb::ByteString queryInfo_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString QueryInfo {
    get { return queryInfo_; }
    set {
      queryInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetObjectCountEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetObjectCountEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DbInfo, other.DbInfo)) return false;
    if (CallbackId != other.CallbackId) return false;
    if (QueryInfo != other.QueryInfo) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (dbInfo_ != null) hash ^= DbInfo.GetHashCode();
    if (CallbackId.Length != 0) hash ^= CallbackId.GetHashCode();
    if (QueryInfo.Length != 0) hash ^= QueryInfo.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (dbInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DbInfo);
    }
    if (CallbackId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(QueryInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (dbInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DbInfo);
    }
    if (CallbackId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CallbackId);
    }
    if (QueryInfo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(QueryInfo);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetObjectCountEvent other) {
    if (other == null) {
      return;
    }
    if (other.dbInfo_ != null) {
      if (dbInfo_ == null) {
        DbInfo = new global::DBInfo();
      }
      DbInfo.MergeFrom(other.DbInfo);
    }
    if (other.CallbackId.Length != 0) {
      CallbackId = other.CallbackId;
    }
    if (other.QueryInfo.Length != 0) {
      QueryInfo = other.QueryInfo;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (dbInfo_ == null) {
            DbInfo = new global::DBInfo();
          }
          input.ReadMessage(DbInfo);
          break;
        }
        case 18: {
          CallbackId = input.ReadString();
          break;
        }
        case 26: {
          QueryInfo = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
