// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.34.0
// source: client.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CallRpc } from "./common";

export const protobufPackage = "";

export interface CreatePlayerEntity {
  entityId: string;
  entityType: string;
  argv: Uint8Array;
}

export interface CreateRemoteEntity {
  entityId: string;
  entityType: string;
  argv: Uint8Array;
}

export interface DeleteRemoteEntity {
  entityId: string;
}

export interface RefreshEntity {
  entityId: string;
  entityType: string;
  argv: Uint8Array;
}

export interface NotifyConnID {
  connId: string;
}

export interface HubRequestClient {
  msgId: string;
  event: CallRpc | undefined;
}

export interface HubResponseClient {
  msgId: string;
  errMsg: string;
  content: Uint8Array;
}

export interface HubNotifyClient {
  event: CallRpc | undefined;
}

function createBaseCreatePlayerEntity(): CreatePlayerEntity {
  return { entityId: "", entityType: "", argv: new Uint8Array(0) };
}

export const CreatePlayerEntity: MessageFns<CreatePlayerEntity> = {
  encode(message: CreatePlayerEntity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityId !== "") {
      writer.uint32(10).string(message.entityId);
    }
    if (message.entityType !== "") {
      writer.uint32(18).string(message.entityType);
    }
    if (message.argv.length !== 0) {
      writer.uint32(26).bytes(message.argv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatePlayerEntity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatePlayerEntity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entityType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.argv = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreatePlayerEntity {
    return {
      entityId: isSet(object.entityId)
        ? globalThis.String(object.entityId)
        : isSet(object.entity_id)
        ? globalThis.String(object.entity_id)
        : "",
      entityType: isSet(object.entityType)
        ? globalThis.String(object.entityType)
        : isSet(object.entity_type)
        ? globalThis.String(object.entity_type)
        : "",
      argv: isSet(object.argv) ? bytesFromBase64(object.argv) : new Uint8Array(0),
    };
  },

  toJSON(message: CreatePlayerEntity): unknown {
    const obj: any = {};
    if (message.entityId !== "") {
      obj.entityId = message.entityId;
    }
    if (message.entityType !== "") {
      obj.entityType = message.entityType;
    }
    if (message.argv.length !== 0) {
      obj.argv = base64FromBytes(message.argv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreatePlayerEntity>, I>>(base?: I): CreatePlayerEntity {
    return CreatePlayerEntity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreatePlayerEntity>, I>>(object: I): CreatePlayerEntity {
    const message = createBaseCreatePlayerEntity();
    message.entityId = object.entityId ?? "";
    message.entityType = object.entityType ?? "";
    message.argv = object.argv ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCreateRemoteEntity(): CreateRemoteEntity {
  return { entityId: "", entityType: "", argv: new Uint8Array(0) };
}

export const CreateRemoteEntity: MessageFns<CreateRemoteEntity> = {
  encode(message: CreateRemoteEntity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityId !== "") {
      writer.uint32(10).string(message.entityId);
    }
    if (message.entityType !== "") {
      writer.uint32(18).string(message.entityType);
    }
    if (message.argv.length !== 0) {
      writer.uint32(26).bytes(message.argv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRemoteEntity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRemoteEntity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entityType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.argv = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateRemoteEntity {
    return {
      entityId: isSet(object.entityId)
        ? globalThis.String(object.entityId)
        : isSet(object.entity_id)
        ? globalThis.String(object.entity_id)
        : "",
      entityType: isSet(object.entityType)
        ? globalThis.String(object.entityType)
        : isSet(object.entity_type)
        ? globalThis.String(object.entity_type)
        : "",
      argv: isSet(object.argv) ? bytesFromBase64(object.argv) : new Uint8Array(0),
    };
  },

  toJSON(message: CreateRemoteEntity): unknown {
    const obj: any = {};
    if (message.entityId !== "") {
      obj.entityId = message.entityId;
    }
    if (message.entityType !== "") {
      obj.entityType = message.entityType;
    }
    if (message.argv.length !== 0) {
      obj.argv = base64FromBytes(message.argv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateRemoteEntity>, I>>(base?: I): CreateRemoteEntity {
    return CreateRemoteEntity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateRemoteEntity>, I>>(object: I): CreateRemoteEntity {
    const message = createBaseCreateRemoteEntity();
    message.entityId = object.entityId ?? "";
    message.entityType = object.entityType ?? "";
    message.argv = object.argv ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDeleteRemoteEntity(): DeleteRemoteEntity {
  return { entityId: "" };
}

export const DeleteRemoteEntity: MessageFns<DeleteRemoteEntity> = {
  encode(message: DeleteRemoteEntity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityId !== "") {
      writer.uint32(10).string(message.entityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteRemoteEntity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteRemoteEntity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteRemoteEntity {
    return {
      entityId: isSet(object.entityId)
        ? globalThis.String(object.entityId)
        : isSet(object.entity_id)
        ? globalThis.String(object.entity_id)
        : "",
    };
  },

  toJSON(message: DeleteRemoteEntity): unknown {
    const obj: any = {};
    if (message.entityId !== "") {
      obj.entityId = message.entityId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteRemoteEntity>, I>>(base?: I): DeleteRemoteEntity {
    return DeleteRemoteEntity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteRemoteEntity>, I>>(object: I): DeleteRemoteEntity {
    const message = createBaseDeleteRemoteEntity();
    message.entityId = object.entityId ?? "";
    return message;
  },
};

function createBaseRefreshEntity(): RefreshEntity {
  return { entityId: "", entityType: "", argv: new Uint8Array(0) };
}

export const RefreshEntity: MessageFns<RefreshEntity> = {
  encode(message: RefreshEntity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityId !== "") {
      writer.uint32(10).string(message.entityId);
    }
    if (message.entityType !== "") {
      writer.uint32(18).string(message.entityType);
    }
    if (message.argv.length !== 0) {
      writer.uint32(26).bytes(message.argv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshEntity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshEntity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entityType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.argv = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshEntity {
    return {
      entityId: isSet(object.entityId)
        ? globalThis.String(object.entityId)
        : isSet(object.entity_id)
        ? globalThis.String(object.entity_id)
        : "",
      entityType: isSet(object.entityType)
        ? globalThis.String(object.entityType)
        : isSet(object.entity_type)
        ? globalThis.String(object.entity_type)
        : "",
      argv: isSet(object.argv) ? bytesFromBase64(object.argv) : new Uint8Array(0),
    };
  },

  toJSON(message: RefreshEntity): unknown {
    const obj: any = {};
    if (message.entityId !== "") {
      obj.entityId = message.entityId;
    }
    if (message.entityType !== "") {
      obj.entityType = message.entityType;
    }
    if (message.argv.length !== 0) {
      obj.argv = base64FromBytes(message.argv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshEntity>, I>>(base?: I): RefreshEntity {
    return RefreshEntity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshEntity>, I>>(object: I): RefreshEntity {
    const message = createBaseRefreshEntity();
    message.entityId = object.entityId ?? "";
    message.entityType = object.entityType ?? "";
    message.argv = object.argv ?? new Uint8Array(0);
    return message;
  },
};

function createBaseNotifyConnID(): NotifyConnID {
  return { connId: "" };
}

export const NotifyConnID: MessageFns<NotifyConnID> = {
  encode(message: NotifyConnID, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connId !== "") {
      writer.uint32(10).string(message.connId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotifyConnID {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotifyConnID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.connId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotifyConnID {
    return {
      connId: isSet(object.connId)
        ? globalThis.String(object.connId)
        : isSet(object.conn_id)
        ? globalThis.String(object.conn_id)
        : "",
    };
  },

  toJSON(message: NotifyConnID): unknown {
    const obj: any = {};
    if (message.connId !== "") {
      obj.connId = message.connId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NotifyConnID>, I>>(base?: I): NotifyConnID {
    return NotifyConnID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NotifyConnID>, I>>(object: I): NotifyConnID {
    const message = createBaseNotifyConnID();
    message.connId = object.connId ?? "";
    return message;
  },
};

function createBaseHubRequestClient(): HubRequestClient {
  return { msgId: "", event: undefined };
}

export const HubRequestClient: MessageFns<HubRequestClient> = {
  encode(message: HubRequestClient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msgId !== "") {
      writer.uint32(10).string(message.msgId);
    }
    if (message.event !== undefined) {
      CallRpc.encode(message.event, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HubRequestClient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHubRequestClient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.event = CallRpc.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HubRequestClient {
    return {
      msgId: isSet(object.msgId)
        ? globalThis.String(object.msgId)
        : isSet(object.msg_id)
        ? globalThis.String(object.msg_id)
        : "",
      event: isSet(object.event) ? CallRpc.fromJSON(object.event) : undefined,
    };
  },

  toJSON(message: HubRequestClient): unknown {
    const obj: any = {};
    if (message.msgId !== "") {
      obj.msgId = message.msgId;
    }
    if (message.event !== undefined) {
      obj.event = CallRpc.toJSON(message.event);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HubRequestClient>, I>>(base?: I): HubRequestClient {
    return HubRequestClient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HubRequestClient>, I>>(object: I): HubRequestClient {
    const message = createBaseHubRequestClient();
    message.msgId = object.msgId ?? "";
    message.event = (object.event !== undefined && object.event !== null)
      ? CallRpc.fromPartial(object.event)
      : undefined;
    return message;
  },
};

function createBaseHubResponseClient(): HubResponseClient {
  return { msgId: "", errMsg: "", content: new Uint8Array(0) };
}

export const HubResponseClient: MessageFns<HubResponseClient> = {
  encode(message: HubResponseClient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msgId !== "") {
      writer.uint32(10).string(message.msgId);
    }
    if (message.errMsg !== "") {
      writer.uint32(18).string(message.errMsg);
    }
    if (message.content.length !== 0) {
      writer.uint32(26).bytes(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HubResponseClient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHubResponseClient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errMsg = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HubResponseClient {
    return {
      msgId: isSet(object.msgId)
        ? globalThis.String(object.msgId)
        : isSet(object.msg_id)
        ? globalThis.String(object.msg_id)
        : "",
      errMsg: isSet(object.errMsg) ? globalThis.String(object.errMsg) : "",
      content: isSet(object.content) ? bytesFromBase64(object.content) : new Uint8Array(0),
    };
  },

  toJSON(message: HubResponseClient): unknown {
    const obj: any = {};
    if (message.msgId !== "") {
      obj.msgId = message.msgId;
    }
    if (message.errMsg !== "") {
      obj.errMsg = message.errMsg;
    }
    if (message.content.length !== 0) {
      obj.content = base64FromBytes(message.content);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HubResponseClient>, I>>(base?: I): HubResponseClient {
    return HubResponseClient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HubResponseClient>, I>>(object: I): HubResponseClient {
    const message = createBaseHubResponseClient();
    message.msgId = object.msgId ?? "";
    message.errMsg = object.errMsg ?? "";
    message.content = object.content ?? new Uint8Array(0);
    return message;
  },
};

function createBaseHubNotifyClient(): HubNotifyClient {
  return { event: undefined };
}

export const HubNotifyClient: MessageFns<HubNotifyClient> = {
  encode(message: HubNotifyClient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event !== undefined) {
      CallRpc.encode(message.event, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HubNotifyClient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHubNotifyClient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event = CallRpc.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HubNotifyClient {
    return { event: isSet(object.event) ? CallRpc.fromJSON(object.event) : undefined };
  },

  toJSON(message: HubNotifyClient): unknown {
    const obj: any = {};
    if (message.event !== undefined) {
      obj.event = CallRpc.toJSON(message.event);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HubNotifyClient>, I>>(base?: I): HubNotifyClient {
    return HubNotifyClient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HubNotifyClient>, I>>(object: I): HubNotifyClient {
    const message = createBaseHubNotifyClient();
    message.event = (object.event !== undefined && object.event !== null)
      ? CallRpc.fromPartial(object.event)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
