syntax = "proto3"; 
import "common.proto";

message ClientRequestReconnect {
	string account_id = 1;
	bytes argv = 2;
}

message ClientRequestService {
	string service_name = 1;
	bytes argv = 2;
}

message GateForwardClientRequestHub {
  string msg_id = 1;
  string entity_id = 2;
  CallRpc event = 3;
}

message GateForwardClientResponseHub {
  string msg_id = 1;
  string entity_id = 2;
  string err_msg = 3;
  bytes content = 4;
}

message GateForwardClientNotifyHub {
  string entity_id = 1;
  CallRpc event = 2;
}

message VersionHandshake {
  uint32 min_version = 1;
  uint32 max_version = 2;
}

message CallBackReliabilityMsg {
  string callback_id = 1;
}