syntax = "proto3"; 
import "common.proto";

message HubCreateRemoteEntity {
  repeated string conn_id = 1;
  string owner_conn_id = 2;
  bool is_direct = 3;
  string entity_id = 4;
  string entity_type = 5;
  bytes argv = 6;
}
 
message HubDeleteRemoteEntity {
  repeated string conn_id = 1;
  string entity_id = 2;
}

message HubRefreshEntity {
  repeated string conn_id = 1;
  string entity_id = 2;
  string entity_type = 3;
  bytes argv = 4;
}

message GateForwardHubRequestClient {
  string conn_id = 1;
  string entity_id = 2;
  CallRpc event = 3;
}

message GateForwardHubResponseClient {
  string conn_id = 1;
  string entity_id = 2;
  string errMsg = 3;
  bytes content = 4;
}

message GateForwardHubNotifyClient {
  repeated string conn_id = 1;
  string entity_id = 2;
  CallRpc event = 3;
}

message GateForwardHubCallGlobal {
  CallRpc event = 1;
}

message HubKickOffClient {
  string conn_id = 1;
  string prompt_info = 2;
}
