syntax = "proto3"; 
import "common.proto";

message GateForwardClientRequestReconnect {
  string gate_name = 1;
  string conn_id = 2;
  string account_id = 3;
  bytes argv = 4;
}

message GateForwardClientRequestService {
  string service_name = 1;
  string gate_name = 2;
  string conn_id = 3;
  bytes argv = 4;
}

message KickOffClient {
  string conn_id = 1;
}

message ClientDisconnnect {
  string conn_id = 1;
}

message ClientRequestHub {
  string conn_id = 1;
  string entity_id = 2;
  string msg_id = 3;
  CallRpc event = 4;
}

message ClientResponseHub {
  string msg_id = 1;
  string errMsg = 2;
  bytes content = 3;
}

message ClientNotifyHub {
  string conn_id = 1;
  string entity_id = 2;
  CallRpc event = 3;
}
